var stackexchange_site_array = {
"stackoverflow" :{name:"Stack Overflow",api_site_parameter:"stackoverflow",site_url:"http://stackoverflow.com",icon_url:"http://sstatic.net/stackoverflow/img/apple-touch-icon.png"},
"serverfault" :{name:"Server Fault",api_site_parameter:"serverfault",site_url:"http://serverfault.com",icon_url:"http://sstatic.net/serverfault/img/apple-touch-icon.png"},
"superuser" :{name:"Super User",api_site_parameter:"superuser",site_url:"http://superuser.com",icon_url:"http://sstatic.net/superuser/img/apple-touch-icon.png"},
"meta.stackoverflow" :{name:"Meta Stack Overflow",api_site_parameter:"meta.stackoverflow",site_url:"http://meta.stackoverflow.com",icon_url:"http://sstatic.net/stackoverflowmeta/img/apple-touch-icon.png"},
"webapps" :{name:"Web Applications",api_site_parameter:"webapps",site_url:"http://webapps.stackexchange.com",icon_url:"http://sstatic.net/webapps/img/apple-touch-icon.png"},
"meta.webapps" :{name:"Web Applications Meta",api_site_parameter:"meta.webapps",site_url:"http://meta.webapps.stackexchange.com",icon_url:"http://sstatic.net/webappsmeta/img/apple-touch-icon.png"},
"gaming" :{name:"Gaming",api_site_parameter:"gaming",site_url:"http://gaming.stackexchange.com",icon_url:"http://sstatic.net/gaming/img/apple-touch-icon.png"},
"meta.gaming" :{name:"Gaming Meta",api_site_parameter:"meta.gaming",site_url:"http://meta.gaming.stackexchange.com",icon_url:"http://sstatic.net/gamingmeta/img/apple-touch-icon.png"},
"webmasters" :{name:"Webmasters",api_site_parameter:"webmasters",site_url:"http://webmasters.stackexchange.com",icon_url:"http://sstatic.net/webmasters/img/apple-touch-icon.png"},
"meta.webmasters" :{name:"Webmasters Meta",api_site_parameter:"meta.webmasters",site_url:"http://meta.webmasters.stackexchange.com",icon_url:"http://sstatic.net/webmastersmeta/img/apple-touch-icon.png"},
"cooking" :{name:"Cooking",api_site_parameter:"cooking",site_url:"http://cooking.stackexchange.com",icon_url:"http://sstatic.net/cooking/img/apple-touch-icon.png"},
"meta.cooking" :{name:"Cooking Meta",api_site_parameter:"meta.cooking",site_url:"http://meta.cooking.stackexchange.com",icon_url:"http://sstatic.net/cookingmeta/img/apple-touch-icon.png"},
"gamedev" :{name:"Game Development",api_site_parameter:"gamedev",site_url:"http://gamedev.stackexchange.com",icon_url:"http://sstatic.net/gamedev/img/apple-touch-icon.png"},
"meta.gamedev" :{name:"Game Development Meta",api_site_parameter:"meta.gamedev",site_url:"http://meta.gamedev.stackexchange.com",icon_url:"http://sstatic.net/gamedevmeta/img/apple-touch-icon.png"},
"photo" :{name:"Photography",api_site_parameter:"photo",site_url:"http://photo.stackexchange.com",icon_url:"http://sstatic.net/photo/img/apple-touch-icon.png"},
"meta.photo" :{name:"Photography Meta",api_site_parameter:"meta.photo",site_url:"http://meta.photo.stackexchange.com",icon_url:"http://sstatic.net/photometa/img/apple-touch-icon.png"},
"stats" :{name:"Statistical Analysis",api_site_parameter:"stats",site_url:"http://stats.stackexchange.com",icon_url:"http://sstatic.net/stats/img/apple-touch-icon.png"},
"meta.stats" :{name:"Statistical Analysis Meta",api_site_parameter:"meta.stats",site_url:"http://meta.stats.stackexchange.com",icon_url:"http://sstatic.net/statsmeta/img/apple-touch-icon.png"},
"math" :{name:"Mathematics",api_site_parameter:"math",site_url:"http://math.stackexchange.com",icon_url:"http://sstatic.net/math/img/apple-touch-icon.png"},
"meta.math" :{name:"Mathematics Meta",api_site_parameter:"meta.math",site_url:"http://meta.math.stackexchange.com",icon_url:"http://sstatic.net/mathmeta/img/apple-touch-icon.png"},
"diy" :{name:"Home Improvement",api_site_parameter:"diy",site_url:"http://diy.stackexchange.com",icon_url:"http://sstatic.net/diy/img/apple-touch-icon.png"},
"meta.diy" :{name:"Home Improvement Meta",api_site_parameter:"meta.diy",site_url:"http://meta.diy.stackexchange.com",icon_url:"http://sstatic.net/diymeta/img/apple-touch-icon.png"},
"meta.superuser" :{name:"Meta Super User",api_site_parameter:"meta.superuser",site_url:"http://meta.superuser.com",icon_url:"http://sstatic.net/superusermeta/img/apple-touch-icon.png"},
"meta.serverfault" :{name:"Meta Server Fault",api_site_parameter:"meta.serverfault",site_url:"http://meta.serverfault.com",icon_url:"http://sstatic.net/serverfaultmeta/img/apple-touch-icon.png"},
"gis" :{name:"GIS",api_site_parameter:"gis",site_url:"http://gis.stackexchange.com",icon_url:"http://sstatic.net/gis/img/apple-touch-icon.png"},
"meta.gis" :{name:"GIS Meta",api_site_parameter:"meta.gis",site_url:"http://meta.gis.stackexchange.com",icon_url:"http://sstatic.net/gismeta/img/apple-touch-icon.png"},
"tex" :{name:"TeX - LaTeX",api_site_parameter:"tex",site_url:"http://tex.stackexchange.com",icon_url:"http://sstatic.net/tex/img/apple-touch-icon.png"},
"meta.tex" :{name:"TeX - LaTeX Meta",api_site_parameter:"meta.tex",site_url:"http://meta.tex.stackexchange.com",icon_url:"http://sstatic.net/texmeta/img/apple-touch-icon.png"},
"askubuntu" :{name:"Ask Ubuntu",api_site_parameter:"askubuntu",site_url:"http://askubuntu.com",icon_url:"http://sstatic.net/askubuntu/img/apple-touch-icon.png"},
"meta.askubuntu" :{name:"Ask Ubuntu Meta",api_site_parameter:"meta.askubuntu",site_url:"http://meta.askubuntu.com",icon_url:"http://sstatic.net/askubuntumeta/img/apple-touch-icon.png"},
"money" :{name:"Personal Finance and Money",api_site_parameter:"money",site_url:"http://money.stackexchange.com",icon_url:"http://sstatic.net/money/img/apple-touch-icon.png"},
"meta.money" :{name:"Personal Finance and Money Meta",api_site_parameter:"meta.money",site_url:"http://meta.money.stackexchange.com",icon_url:"http://sstatic.net/moneymeta/img/apple-touch-icon.png"},
"english" :{name:"English Language and Usage",api_site_parameter:"english",site_url:"http://english.stackexchange.com",icon_url:"http://sstatic.net/english/img/apple-touch-icon.png"},
"meta.english" :{name:"English Language and Usage Meta",api_site_parameter:"meta.english",site_url:"http://meta.english.stackexchange.com",icon_url:"http://sstatic.net/englishmeta/img/apple-touch-icon.png"},
"stackapps" :{name:"Stack Apps",api_site_parameter:"stackapps",site_url:"http://stackapps.com",icon_url:"http://sstatic.net/stackapps/img/apple-touch-icon.png"},
"ux" :{name:"User Experience",api_site_parameter:"ux",site_url:"http://ux.stackexchange.com",icon_url:"http://sstatic.net/ux/img/apple-touch-icon.png"},
"meta.ux" :{name:"User Experience Meta",api_site_parameter:"meta.ux",site_url:"http://meta.ux.stackexchange.com",icon_url:"http://sstatic.net/uxmeta/img/apple-touch-icon.png"},
"unix" :{name:"Unix and Linux",api_site_parameter:"unix",site_url:"http://unix.stackexchange.com",icon_url:"http://sstatic.net/unix/img/apple-touch-icon.png"},
"meta.unix" :{name:"Unix and Linux Meta",api_site_parameter:"meta.unix",site_url:"http://meta.unix.stackexchange.com",icon_url:"http://sstatic.net/unixmeta/img/apple-touch-icon.png"},
"wordpress" :{name:"WordPress",api_site_parameter:"wordpress",site_url:"http://wordpress.stackexchange.com",icon_url:"http://sstatic.net/wordpress/img/apple-touch-icon.png"},
"meta.wordpress" :{name:"WordPress Meta",api_site_parameter:"meta.wordpress",site_url:"http://meta.wordpress.stackexchange.com",icon_url:"http://sstatic.net/wordpressmeta/img/apple-touch-icon.png"},
"cstheory" :{name:"Theoretical Computer Science",api_site_parameter:"cstheory",site_url:"http://cstheory.stackexchange.com",icon_url:"http://sstatic.net/cstheory/img/apple-touch-icon.png"},
"meta.cstheory" :{name:"Theoretical Computer Science Meta",api_site_parameter:"meta.cstheory",site_url:"http://meta.cstheory.stackexchange.com",icon_url:"http://sstatic.net/cstheorymeta/img/apple-touch-icon.png"},
"apple" :{name:"Apple",api_site_parameter:"apple",site_url:"http://apple.stackexchange.com",icon_url:"http://sstatic.net/apple/img/apple-touch-icon.png"},
"meta.apple" :{name:"Apple Meta",api_site_parameter:"meta.apple",site_url:"http://meta.apple.stackexchange.com",icon_url:"http://sstatic.net/applemeta/img/apple-touch-icon.png"},
"rpg" :{name:"Role-playing Games",api_site_parameter:"rpg",site_url:"http://rpg.stackexchange.com",icon_url:"http://sstatic.net/rpg/img/apple-touch-icon.png"},
"meta.rpg" :{name:"Role-playing Games Meta",api_site_parameter:"meta.rpg",site_url:"http://meta.rpg.stackexchange.com",icon_url:"http://sstatic.net/rpgmeta/img/apple-touch-icon.png"},
"bicycles" :{name:"Bicycles",api_site_parameter:"bicycles",site_url:"http://bicycles.stackexchange.com",icon_url:"http://sstatic.net/bicycles/img/apple-touch-icon.png"},
"meta.bicycles" :{name:"Bicycles Meta",api_site_parameter:"meta.bicycles",site_url:"http://meta.bicycles.stackexchange.com",icon_url:"http://sstatic.net/bicyclesmeta/img/apple-touch-icon.png"},
"programmers" :{name:"Programmers",api_site_parameter:"programmers",site_url:"http://programmers.stackexchange.com",icon_url:"http://sstatic.net/programmers/img/apple-touch-icon.png"},
"meta.programmers" :{name:"Programmers Meta",api_site_parameter:"meta.programmers",site_url:"http://meta.programmers.stackexchange.com",icon_url:"http://sstatic.net/programmersmeta/img/apple-touch-icon.png"},
"electronics" :{name:"Electrical Engineering",api_site_parameter:"electronics",site_url:"http://electronics.stackexchange.com",icon_url:"http://sstatic.net/electronics/img/apple-touch-icon.png"},
"meta.electronics" :{name:"Electrical Engineering Meta",api_site_parameter:"meta.electronics",site_url:"http://meta.electronics.stackexchange.com",icon_url:"http://sstatic.net/electronicsmeta/img/apple-touch-icon.png"},
"android" :{name:"Android Enthusiasts",api_site_parameter:"android",site_url:"http://android.stackexchange.com",icon_url:"http://sstatic.net/android/img/apple-touch-icon.png"},
"meta.android" :{name:"Android Enthusiasts Meta",api_site_parameter:"meta.android",site_url:"http://meta.android.stackexchange.com",icon_url:"http://sstatic.net/androidmeta/img/apple-touch-icon.png"},
"answers.onstartups" :{name:"OnStartups",api_site_parameter:"answers.onstartups",site_url:"http://answers.onstartups.com",icon_url:"http://sstatic.net/onstartups/img/apple-touch-icon.png"},
"meta.answers.onstartups" :{name:"OnStartups Meta",api_site_parameter:"meta.answers.onstartups",site_url:"http://meta.answers.onstartups.com",icon_url:"http://sstatic.net/onstartupsmeta/img/apple-touch-icon.png"},
"boardgames" :{name:"Board and Card Games",api_site_parameter:"boardgames",site_url:"http://boardgames.stackexchange.com",icon_url:"http://sstatic.net/boardgames/img/apple-touch-icon.png"},
"meta.boardgames" :{name:"Board and Card Games Meta",api_site_parameter:"meta.boardgames",site_url:"http://meta.boardgames.stackexchange.com",icon_url:"http://sstatic.net/boardgamesmeta/img/apple-touch-icon.png"},
"physics" :{name:"Physics",api_site_parameter:"physics",site_url:"http://physics.stackexchange.com",icon_url:"http://sstatic.net/physics/img/apple-touch-icon.png"},
"meta.physics" :{name:"Physics Meta",api_site_parameter:"meta.physics",site_url:"http://meta.physics.stackexchange.com",icon_url:"http://sstatic.net/physicsmeta/img/apple-touch-icon.png"},
"homebrew" :{name:"Homebrew",api_site_parameter:"homebrew",site_url:"http://homebrew.stackexchange.com",icon_url:"http://sstatic.net/homebrew/img/apple-touch-icon.png"},
"meta.homebrew" :{name:"Homebrew Meta",api_site_parameter:"meta.homebrew",site_url:"http://meta.homebrew.stackexchange.com",icon_url:"http://sstatic.net/homebrewmeta/img/apple-touch-icon.png"},
"security" :{name:"IT Security",api_site_parameter:"security",site_url:"http://security.stackexchange.com",icon_url:"http://sstatic.net/security/img/apple-touch-icon.png"},
"meta.security" :{name:"IT Security Meta",api_site_parameter:"meta.security",site_url:"http://meta.security.stackexchange.com",icon_url:"http://sstatic.net/securitymeta/img/apple-touch-icon.png"},
"writers" :{name:"Writers",api_site_parameter:"writers",site_url:"http://writers.stackexchange.com",icon_url:"http://sstatic.net/writers/img/apple-touch-icon.png"},
"meta.writers" :{name:"Writers Meta",api_site_parameter:"meta.writers",site_url:"http://meta.writers.stackexchange.com",icon_url:"http://sstatic.net/writersmeta/img/apple-touch-icon.png"},
"avp" :{name:"Audio-Video Production",api_site_parameter:"avp",site_url:"http://avp.stackexchange.com",icon_url:"http://sstatic.net/avp/img/apple-touch-icon.png"},
"meta.avp" :{name:"Audio-Video Production Meta",api_site_parameter:"meta.avp",site_url:"http://meta.avp.stackexchange.com",icon_url:"http://sstatic.net/avpmeta/img/apple-touch-icon.png"},
"graphicdesign" :{name:"Graphic Design",api_site_parameter:"graphicdesign",site_url:"http://graphicdesign.stackexchange.com",icon_url:"http://sstatic.net/graphicdesign/img/apple-touch-icon.png"},
"meta.graphicdesign" :{name:"Graphic Design Meta",api_site_parameter:"meta.graphicdesign",site_url:"http://meta.graphicdesign.stackexchange.com",icon_url:"http://sstatic.net/graphicdesignmeta/img/apple-touch-icon.png"},
"dba" :{name:"Database Administrators",api_site_parameter:"dba",site_url:"http://dba.stackexchange.com",icon_url:"http://sstatic.net/dba/img/apple-touch-icon.png"},
"meta.dba" :{name:"Database Administrators Meta",api_site_parameter:"meta.dba",site_url:"http://meta.dba.stackexchange.com",icon_url:"http://sstatic.net/dbameta/img/apple-touch-icon.png"},
"scifi" :{name:"Science Fiction and Fantasy",api_site_parameter:"scifi",site_url:"http://scifi.stackexchange.com",icon_url:"http://sstatic.net/scifi/img/apple-touch-icon.png"},
"meta.scifi" :{name:"Science Fiction and Fantasy Meta",api_site_parameter:"meta.scifi",site_url:"http://meta.scifi.stackexchange.com",icon_url:"http://sstatic.net/scifimeta/img/apple-touch-icon.png"},
"discuss.area51" :{name:"Area 51 Discussions",api_site_parameter:"discuss.area51",site_url:"http://discuss.area51.stackexchange.com",icon_url:"http://sstatic.net/area51discuss/img/apple-touch-icon.png"},
"codereview" :{name:"Code Review",api_site_parameter:"codereview",site_url:"http://codereview.stackexchange.com",icon_url:"http://sstatic.net/codereview/img/apple-touch-icon.png"},
"meta.codereview" :{name:"Code Review Meta",api_site_parameter:"meta.codereview",site_url:"http://meta.codereview.stackexchange.com",icon_url:"http://sstatic.net/codereviewmeta/img/apple-touch-icon.png"},
"codegolf" :{name:"Code Golf",api_site_parameter:"codegolf",site_url:"http://codegolf.stackexchange.com",icon_url:"http://sstatic.net/codegolf/img/apple-touch-icon.png"},
"meta.codegolf" :{name:"Code Golf Meta",api_site_parameter:"meta.codegolf",site_url:"http://meta.codegolf.stackexchange.com",icon_url:"http://sstatic.net/codegolfmeta/img/apple-touch-icon.png"},
"quant" :{name:"Quantitative Finance",api_site_parameter:"quant",site_url:"http://quant.stackexchange.com",icon_url:"http://sstatic.net/quant/img/apple-touch-icon.png"},
"meta.quant" :{name:"Quantitative Finance Meta",api_site_parameter:"meta.quant",site_url:"http://meta.quant.stackexchange.com",icon_url:"http://sstatic.net/quantmeta/img/apple-touch-icon.png"},
"pm" :{name:"Project Management",api_site_parameter:"pm",site_url:"http://pm.stackexchange.com",icon_url:"http://sstatic.net/pm/img/apple-touch-icon.png"},
"meta.pm" :{name:"Project Management Meta",api_site_parameter:"meta.pm",site_url:"http://meta.pm.stackexchange.com",icon_url:"http://sstatic.net/pmmeta/img/apple-touch-icon.png"},
"skeptics" :{name:"Skeptics",api_site_parameter:"skeptics",site_url:"http://skeptics.stackexchange.com",icon_url:"http://sstatic.net/skeptics/img/apple-touch-icon.png"},
"meta.skeptics" :{name:"Skeptics Meta",api_site_parameter:"meta.skeptics",site_url:"http://meta.skeptics.stackexchange.com",icon_url:"http://sstatic.net/skepticsmeta/img/apple-touch-icon.png"},
"fitness" :{name:"Fitness and Nutrition",api_site_parameter:"fitness",site_url:"http://fitness.stackexchange.com",icon_url:"http://sstatic.net/fitness/img/apple-touch-icon.png"},
"meta.fitness" :{name:"Fitness and Nutrition Meta",api_site_parameter:"meta.fitness",site_url:"http://meta.fitness.stackexchange.com",icon_url:"http://sstatic.net/fitnessmeta/img/apple-touch-icon.png"},
"drupal" :{name:"Drupal Answers",api_site_parameter:"drupal",site_url:"http://drupal.stackexchange.com",icon_url:"http://sstatic.net/drupal/img/apple-touch-icon.png"},
"meta.drupal" :{name:"Drupal Answers Meta",api_site_parameter:"meta.drupal",site_url:"http://meta.drupal.stackexchange.com",icon_url:"http://sstatic.net/drupalmeta/img/apple-touch-icon.png"},
"mechanics" :{name:"Motor Vehicle Maintenance and Repair",api_site_parameter:"mechanics",site_url:"http://mechanics.stackexchange.com",icon_url:"http://sstatic.net/mechanics/img/apple-touch-icon.png"},
"meta.mechanics" :{name:"Motor Vehicle Maintenance and Repair Meta",api_site_parameter:"meta.mechanics",site_url:"http://meta.mechanics.stackexchange.com",icon_url:"http://sstatic.net/mechanicsmeta/img/apple-touch-icon.png"},
"parenting" :{name:"Parenting",api_site_parameter:"parenting",site_url:"http://parenting.stackexchange.com",icon_url:"http://sstatic.net/parenting/img/apple-touch-icon.png"},
"meta.parenting" :{name:"Parenting Meta",api_site_parameter:"meta.parenting",site_url:"http://meta.parenting.stackexchange.com",icon_url:"http://sstatic.net/parentingmeta/img/apple-touch-icon.png"},
"sharepoint" :{name:"SharePoint",api_site_parameter:"sharepoint",site_url:"http://sharepoint.stackexchange.com",icon_url:"http://sstatic.net/sharepoint/img/apple-touch-icon.png"},
"meta.sharepoint" :{name:"SharePoint Meta",api_site_parameter:"meta.sharepoint",site_url:"http://meta.sharepoint.stackexchange.com",icon_url:"http://sstatic.net/sharepointmeta/img/apple-touch-icon.png"},
"music" :{name:"Musical Practice and Performance",api_site_parameter:"music",site_url:"http://music.stackexchange.com",icon_url:"http://sstatic.net/music/img/apple-touch-icon.png"},
"meta.music" :{name:"Musical Practice and Performance Meta",api_site_parameter:"meta.music",site_url:"http://meta.music.stackexchange.com",icon_url:"http://sstatic.net/musicmeta/img/apple-touch-icon.png"},
"sqa" :{name:"Software Quality Assurance and Testing",api_site_parameter:"sqa",site_url:"http://sqa.stackexchange.com",icon_url:"http://sstatic.net/sqa/img/apple-touch-icon.png"},
"meta.sqa" :{name:"Software Quality Assurance and Testing Meta",api_site_parameter:"meta.sqa",site_url:"http://meta.sqa.stackexchange.com",icon_url:"http://sstatic.net/sqameta/img/apple-touch-icon.png"},
"judaism" :{name:"Jewish Life and Learning",api_site_parameter:"judaism",site_url:"http://judaism.stackexchange.com",icon_url:"http://sstatic.net/judaism/img/apple-touch-icon.png"},
"meta.judaism" :{name:"Jewish Life and Learning Meta",api_site_parameter:"meta.judaism",site_url:"http://meta.judaism.stackexchange.com",icon_url:"http://sstatic.net/judaismmeta/img/apple-touch-icon.png"},
"german" :{name:"German Language and Usage",api_site_parameter:"german",site_url:"http://german.stackexchange.com",icon_url:"http://sstatic.net/german/img/apple-touch-icon.png"},
"meta.german" :{name:"German Language and Usage Meta",api_site_parameter:"meta.german",site_url:"http://meta.german.stackexchange.com",icon_url:"http://sstatic.net/germanmeta/img/apple-touch-icon.png"},
"japanese" :{name:"Japanese Language and Usage",api_site_parameter:"japanese",site_url:"http://japanese.stackexchange.com",icon_url:"http://sstatic.net/japanese/img/apple-touch-icon.png"},
"meta.japanese" :{name:"Japanese Language and Usage Meta",api_site_parameter:"meta.japanese",site_url:"http://meta.japanese.stackexchange.com",icon_url:"http://sstatic.net/japanesemeta/img/apple-touch-icon.png"},
"astronomy" :{name:"Astronomy",api_site_parameter:"astronomy",site_url:"http://astronomy.stackexchange.com",icon_url:"http://sstatic.net/astronomy/img/apple-touch-icon.png"},
"meta.astronomy" :{name:"Astronomy Meta",api_site_parameter:"meta.astronomy",site_url:"http://meta.astronomy.stackexchange.com",icon_url:"http://sstatic.net/astronomymeta/img/apple-touch-icon.png"},
"philosophy" :{name:"Philosophy",api_site_parameter:"philosophy",site_url:"http://philosophy.stackexchange.com",icon_url:"http://sstatic.net/philosophy/img/apple-touch-icon.png"},
"meta.philosophy" :{name:"Philosophy Meta",api_site_parameter:"meta.philosophy",site_url:"http://meta.philosophy.stackexchange.com",icon_url:"http://sstatic.net/philosophymeta/img/apple-touch-icon.png"},
"gardening" :{name:"Gardening and Landscaping",api_site_parameter:"gardening",site_url:"http://gardening.stackexchange.com",icon_url:"http://sstatic.net/gardening/img/apple-touch-icon.png"},
"meta.gardening" :{name:"Gardening and Landscaping Meta",api_site_parameter:"meta.gardening",site_url:"http://meta.gardening.stackexchange.com",icon_url:"http://sstatic.net/gardeningmeta/img/apple-touch-icon.png"},
"travel" :{name:"Travel",api_site_parameter:"travel",site_url:"http://travel.stackexchange.com",icon_url:"http://sstatic.net/travel/img/apple-touch-icon.png"},
"meta.travel" :{name:"Travel Meta",api_site_parameter:"meta.travel",site_url:"http://meta.travel.stackexchange.com",icon_url:"http://sstatic.net/travelmeta/img/apple-touch-icon.png"},
"productivity" :{name:"Personal Productivity",api_site_parameter:"productivity",site_url:"http://productivity.stackexchange.com",icon_url:"http://sstatic.net/productivity/img/apple-touch-icon.png"},
"meta.productivity" :{name:"Personal Productivity Meta",api_site_parameter:"meta.productivity",site_url:"http://meta.productivity.stackexchange.com",icon_url:"http://sstatic.net/productivitymeta/img/apple-touch-icon.png"},
"crypto" :{name:"Cryptography",api_site_parameter:"crypto",site_url:"http://crypto.stackexchange.com",icon_url:"http://sstatic.net/crypto/img/apple-touch-icon.png"},
"meta.crypto" :{name:"Cryptography Meta",api_site_parameter:"meta.crypto",site_url:"http://meta.crypto.stackexchange.com",icon_url:"http://sstatic.net/cryptometa/img/apple-touch-icon.png"},
"literature" :{name:"Literature",api_site_parameter:"literature",site_url:"http://literature.stackexchange.com",icon_url:"http://sstatic.net/literature/img/apple-touch-icon.png"},
"meta.literature" :{name:"Literature Meta",api_site_parameter:"meta.literature",site_url:"http://meta.literature.stackexchange.com",icon_url:"http://sstatic.net/literaturemeta/img/apple-touch-icon.png"},
"dsp" :{name:"Signal Processing",api_site_parameter:"dsp",site_url:"http://dsp.stackexchange.com",icon_url:"http://sstatic.net/dsp/img/apple-touch-icon.png"},
"meta.dsp" :{name:"Signal Processing Meta",api_site_parameter:"meta.dsp",site_url:"http://meta.dsp.stackexchange.com",icon_url:"http://sstatic.net/dspmeta/img/apple-touch-icon.png"},
"french" :{name:"French Language and Usage",api_site_parameter:"french",site_url:"http://french.stackexchange.com",icon_url:"http://sstatic.net/french/img/apple-touch-icon.png"},
"meta.french" :{name:"French Language and Usage Meta",api_site_parameter:"meta.french",site_url:"http://meta.french.stackexchange.com",icon_url:"http://sstatic.net/frenchmeta/img/apple-touch-icon.png"},
"christianity" :{name:"Christianity",api_site_parameter:"christianity",site_url:"http://christianity.stackexchange.com",icon_url:"http://sstatic.net/christianity/img/apple-touch-icon.png"},
"meta.christianity" :{name:"Christianity Meta",api_site_parameter:"meta.christianity",site_url:"http://meta.christianity.stackexchange.com",icon_url:"http://sstatic.net/christianitymeta/img/apple-touch-icon.png"},
"bitcoin" :{name:"Bitcoin",api_site_parameter:"bitcoin",site_url:"http://bitcoin.stackexchange.com",icon_url:"http://sstatic.net/bitcoin/img/apple-touch-icon.png"},
"meta.bitcoin" :{name:"Bitcoin Meta",api_site_parameter:"meta.bitcoin",site_url:"http://meta.bitcoin.stackexchange.com",icon_url:"http://sstatic.net/bitcoinmeta/img/apple-touch-icon.png"},
"linguistics" :{name:"Linguistics",api_site_parameter:"linguistics",site_url:"http://linguistics.stackexchange.com",icon_url:"http://sstatic.net/linguistics/img/apple-touch-icon.png"},
"meta.linguistics" :{name:"Linguistics Meta",api_site_parameter:"meta.linguistics",site_url:"http://meta.linguistics.stackexchange.com",icon_url:"http://sstatic.net/linguisticsmeta/img/apple-touch-icon.png"},
"theoreticalphysics" :{name:"Theoretical Physics",api_site_parameter:"theoreticalphysics",site_url:"http://theoreticalphysics.stackexchange.com",icon_url:"http://sstatic.net/theoreticalphysics/img/apple-touch-icon.png"},
"meta.theoreticalphysics" :{name:"Theoretical Physics Meta",api_site_parameter:"meta.theoreticalphysics",site_url:"http://meta.theoreticalphysics.stackexchange.com",icon_url:"http://sstatic.net/theoreticalphysicsmeta/img/apple-touch-icon.png"},
"hermeneutics" :{name:"Biblical Hermeneutics",api_site_parameter:"hermeneutics",site_url:"http://hermeneutics.stackexchange.com",icon_url:"http://sstatic.net/hermeneutics/img/apple-touch-icon.png"},
"meta.hermeneutics" :{name:"Biblical Hermeneutics Meta",api_site_parameter:"meta.hermeneutics",site_url:"http://meta.hermeneutics.stackexchange.com",icon_url:"http://sstatic.net/hermeneuticsmeta/img/apple-touch-icon.png"},
"history" :{name:"History",api_site_parameter:"history",site_url:"http://history.stackexchange.com",icon_url:"http://sstatic.net/history/img/apple-touch-icon.png"},
"meta.history" :{name:"History Meta",api_site_parameter:"meta.history",site_url:"http://meta.history.stackexchange.com",icon_url:"http://sstatic.net/historymeta/img/apple-touch-icon.png"},
"economics" :{name:"Economics",api_site_parameter:"economics",site_url:"http://economics.stackexchange.com",icon_url:"http://sstatic.net/economics/img/apple-touch-icon.png"},
"meta.economics" :{name:"Economics Meta",api_site_parameter:"meta.economics",site_url:"http://meta.economics.stackexchange.com",icon_url:"http://sstatic.net/economicsmeta/img/apple-touch-icon.png"},
"healthcareit" :{name:"Healthcare IT",api_site_parameter:"healthcareit",site_url:"http://healthcareit.stackexchange.com",icon_url:"http://sstatic.net/healthcareit/img/apple-touch-icon.png"},
"meta.healthcareit" :{name:"Healthcare IT Meta",api_site_parameter:"meta.healthcareit",site_url:"http://meta.healthcareit.stackexchange.com",icon_url:"http://sstatic.net/healthcareitmeta/img/apple-touch-icon.png"},
"bricks" :{name:"LEGO&#174; Answers",api_site_parameter:"bricks",site_url:"http://bricks.stackexchange.com",icon_url:"http://sstatic.net/bricks/img/apple-touch-icon.png"},
"meta.bricks" :{name:"LEGO&#174; Answers Meta",api_site_parameter:"meta.bricks",site_url:"http://meta.bricks.stackexchange.com",icon_url:"http://sstatic.net/bricksmeta/img/apple-touch-icon.png"},
"firearms" :{name:"Firearms",api_site_parameter:"firearms",site_url:"http://firearms.stackexchange.com",icon_url:"http://sstatic.net/firearms/img/apple-touch-icon.png"},
"meta.firearms" :{name:"Firearms Meta",api_site_parameter:"meta.firearms",site_url:"http://meta.firearms.stackexchange.com",icon_url:"http://sstatic.net/firearmsmeta/img/apple-touch-icon.png"},
"spanish" :{name:"Spanish Language and Usage",api_site_parameter:"spanish",site_url:"http://spanish.stackexchange.com",icon_url:"http://sstatic.net/spanish/img/apple-touch-icon.png"},
"meta.spanish" :{name:"Spanish Language and Usage Meta",api_site_parameter:"meta.spanish",site_url:"http://meta.spanish.stackexchange.com",icon_url:"http://sstatic.net/spanishmeta/img/apple-touch-icon.png"},
"scicomp" :{name:"Computational Science",api_site_parameter:"scicomp",site_url:"http://scicomp.stackexchange.com",icon_url:"http://sstatic.net/scicomp/img/apple-touch-icon.png"},
"meta.scicomp" :{name:"Computational Science Meta",api_site_parameter:"meta.scicomp",site_url:"http://meta.scicomp.stackexchange.com",icon_url:"http://sstatic.net/scicompmeta/img/apple-touch-icon.png"},
"movies" :{name:"Movies and TV",api_site_parameter:"movies",site_url:"http://movies.stackexchange.com",icon_url:"http://sstatic.net/movies/img/apple-touch-icon.png"},
"meta.movies" :{name:"Movies and TV Meta",api_site_parameter:"meta.movies",site_url:"http://meta.movies.stackexchange.com",icon_url:"http://sstatic.net/moviesmeta/img/apple-touch-icon.png"},
"chinese" :{name:"Chinese Language and Usage",api_site_parameter:"chinese",site_url:"http://chinese.stackexchange.com",icon_url:"http://sstatic.net/chinese/img/apple-touch-icon.png"},
"meta.chinese" :{name:"Chinese Language and Usage Meta",api_site_parameter:"meta.chinese",site_url:"http://meta.chinese.stackexchange.com",icon_url:"http://sstatic.net/chinesemeta/img/apple-touch-icon.png"},
"biology" :{name:"Biology",api_site_parameter:"biology",site_url:"http://biology.stackexchange.com",icon_url:"http://sstatic.net/biology/img/apple-touch-icon.png"},
"meta.biology" :{name:"Biology Meta",api_site_parameter:"meta.biology",site_url:"http://meta.biology.stackexchange.com",icon_url:"http://sstatic.net/biologymeta/img/apple-touch-icon.png"},
"poker" :{name:"Poker",api_site_parameter:"poker",site_url:"http://poker.stackexchange.com",icon_url:"http://sstatic.net/poker/img/apple-touch-icon.png"},
"meta.poker" :{name:"Poker Meta",api_site_parameter:"meta.poker",site_url:"http://meta.poker.stackexchange.com",icon_url:"http://sstatic.net/pokermeta/img/apple-touch-icon.png"},
"sexuality" :{name:"Sexuality",api_site_parameter:"sexuality",site_url:"http://sexuality.stackexchange.com",icon_url:"http://sstatic.net/sexuality/img/apple-touch-icon.png"},
"meta.sexuality" :{name:"Sexuality Meta",api_site_parameter:"meta.sexuality",site_url:"http://meta.sexuality.stackexchange.com",icon_url:"http://sstatic.net/sexualitymeta/img/apple-touch-icon.png"},
"mathematica" :{name:"Mathematica",api_site_parameter:"mathematica",site_url:"http://mathematica.stackexchange.com",icon_url:"http://sstatic.net/mathematica/img/apple-touch-icon.png"},
"meta.mathematica" :{name:"Mathematica Meta",api_site_parameter:"meta.mathematica",site_url:"http://meta.mathematica.stackexchange.com",icon_url:"http://sstatic.net/mathematicameta/img/apple-touch-icon.png"},
"cogsci" :{name:"Cognitive Sciences",api_site_parameter:"cogsci",site_url:"http://cogsci.stackexchange.com",icon_url:"http://sstatic.net/cogsci/img/apple-touch-icon.png"},
"meta.cogsci" :{name:"Cognitive Sciences Meta",api_site_parameter:"meta.cogsci",site_url:"http://meta.cogsci.stackexchange.com",icon_url:"http://sstatic.net/cogscimeta/img/apple-touch-icon.png"},};
